fg2: <main> function()
  block 0: [entry]
    node 0: constant[undefined,v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js)
    ->[block 1]
  block 1:
    node 1: constant["tajs-host-env:string-replace-model.js",v2] (host-environment-sources-loader)
    node 2: constant[true,v3] (host-environment-sources-loader)
    ->[block 2]
  block 2:
    node 3: call[TAJS_load,v2,v3,v4] (host-environment-sources-loader)
    ->[block 3]
  block 3:
    node 4: call[-,v4,-] (host-environment-sources-loader)
    ->[block 4]
  block 4:
    node 5: constant["tajs-host-env:error-captureStackTrace-model.js",v5] (host-environment-sources-loader)
    node 6: constant[true,v6] (host-environment-sources-loader)
    ->[block 5]
  block 5:
    node 7: call[TAJS_load,v5,v6,v7] (host-environment-sources-loader)
    ->[block 6]
  block 6:
    node 8: call[-,v7,-] (host-environment-sources-loader)
    ->[block 7]
  block 7:
    node 9: function-expr[function g(),v8] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:5)
    node 10: write-variable[v8,'f'] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:1)
    ->[block 8]
  block 8: [exit-ordinary]
    node 11: return[v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js)
    ->[]
  block 9: [exit-exceptional]
    node 12: exceptional-return (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js)
    ->[]
function g()
  block 10: [entry]
    node 13: constant[undefined,v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:5)
    ->[block 11]
  block 11: [exit-ordinary]
    node 14: return[v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:5)
    ->[]
  block 12: [exit-exceptional]
    node 15: exceptional-return (test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:5)
    ->[]

test-resources/src/flowgraphbuilder/flowgraph_builder0122.js: [definite] Exceptional program exit is unreachable
test-resources/src/flowgraphbuilder/flowgraph_builder0122.js:1:5: [definite] Unreachable function g
Soundness testing succeeded for 2 checks (with 0 expected failures)
